services:
  - type: web
    name: mips-pipeline-simulator
    env: python
    rootDir: web
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.2
